Task_78 : Use role to check admin user
N-Viet-ruby-dev/quiz-intern-batch-1 pull request #18
Opened 2019-05-28 08:44 UTC by nguyenvanhung1995

2019-05-28 09:02 UTC, dangminhthinh1612 commented on app/views/admin/users/_form_user.html.erb
> +                <%= f.label :role %>
Cả create và update đều change role được thì sao phải lệnh if nữa

2019-05-28 09:02 UTC, dangminhthinh1612 commented on app/views/admin/users/index.html.erb
> +                  <td><%= user.role %></td>
Thay đổi viết hoa vai trò User, Admin

2019-05-30 02:59 UTC, k-tri requested changes

2019-05-30 02:59 UTC, k-tri commented on app/views/admin/users/_form_user.html.erb
> +              <%= f.select :role, ["admin", "user"], {},
dùng User.roles.keys

2019-05-30 02:59 UTC, k-tri commented on app/views/admin/users/index.html.erb
> +                </tr>
thêm thẻ th

2019-05-30 03:00 UTC, N-Viet-ruby-dev approved these changes

2019-05-30 03:02 UTC, merged