Task 26, Play quiz and show result
N-Viet-ruby-dev/quiz-intern-batch-1 pull request #19
Opened 2019-05-29 09:27 UTC by dangminhthinh1612

2019-05-29 09:32 UTC, N-Viet-ruby-dev commented on app/models/test.rb
> -  belongs_to :user
`belongs_to :user, optional: true`

2019-05-29 09:32 UTC, N-Viet-ruby-dev commented on app/models/test.rb
> +  delegate :id, to: :user, allow_nil: true, prefix: :guest
Không cần cái này

2019-05-29 09:33 UTC, N-Viet-ruby-dev commented on app/views/admin/tests/index.html.erb
> -                <td><%= test.user.name %></td>
`test.user_name || "Guest"`

2019-05-29 15:34 UTC, dangminhthinh1612 commented on app/views/admin/tests/index.html.erb
> -                <td><%= test.user.name %></td>
em có sửa lại thành như này ạ:
`test.user ? test.user.name : "Guest"`

2019-05-30 01:15 UTC, N-Viet-ruby-dev commented on app/controllers/tests_controller.rb
> +  def new
thêm dòng trống giữa các method

2019-05-30 01:16 UTC, N-Viet-ruby-dev commented on app/controllers/tests_controller.rb
> +  before_action :check_answer, only: :create
không cần dòng này

2019-05-30 01:19 UTC, N-Viet-ruby-dev commented on app/models/detail_test.rb
> +  belongs_to :answer, optional: true
`optional: true` tại sao lại cần cái này

2019-05-30 01:19 UTC, N-Viet-ruby-dev commented on app/controllers/tests_controller.rb
> +    params[:test][:detail_tests_attributes].each{|k, v|
dùng test.detail_tests để tính

2019-05-30 01:31 UTC, dangminhthinh1612 commented on app/models/detail_test.rb
> +  belongs_to :answer, optional: true
Em có check phần làm bài thì do chưa thể load từng câu hỏi riêng rẽ, để đảm bảo người dùng làm 5 câu mới trả về kết quả. Nên khi người dùng không làm câu nào thì chỗ lệnh quanh answer hỗ trợ nil ạ

2019-05-30 01:40 UTC, dangminhthinh1612 commented on app/controllers/tests_controller.rb
> +    params[:test][:detail_tests_attributes].each{|k, v|
Em chưa nắm được làm sao lấy test.detail_test khi mà chưa create ạ
em tính trước khi save @test, và chỉ có params là có giá trị thôi chứ ạ

2019-05-30 02:03 UTC, N-Viet-ruby-dev commented on app/controllers/tests_controller.rb
> +    params[:test][:detail_tests_attributes].each{|k, v|
Cái `@test = Test.new test_params` nếu chạy đúng thì @test sẽ có `@test.detail_tests` để sử dụng rồi

2019-05-30 02:46 UTC, k-tri requested changes

2019-05-30 02:46 UTC, k-tri commented on app/controllers/tests_controller.rb
> +    @test.detail_tests.each{|key|
- quá 1 dòng thì dùng do ... end
- dùng delegate trong detail_test model để lấy giá trị is_correct từ answer
-> @test.detail_tests.select{|e| e.is_correct}.count

2019-05-30 03:02 UTC, dangminhthinh1612 commented on app/controllers/tests_controller.rb
> +    @test.detail_tests.each{|key|
:v giờ em mới biết cái này :0

2019-05-30 03:12 UTC, N-Viet-ruby-dev commented on app/controllers/tests_controller.rb
> +    @category = Category.find params[:format]
Dùng nested_resources để lấy được params[:category_id]

2019-05-30 03:14 UTC, N-Viet-ruby-dev commented on app/models/detail_test.rb
> +  delegate :is_correct, to: :answer
`allow_nil: true`

2019-05-30 03:15 UTC, dangminhthinh1612 commented on app/models/detail_test.rb
> +  delegate :is_correct, to: :answer
em tưởng là có optional: true rồi thì không cần allow_nil ?

2019-05-30 03:34 UTC, N-Viet-ruby-dev approved these changes

2019-05-30 03:34 UTC, merged